// Truestead Law — Florida Medicaid planning article cluster (batch 1, 9/24/2026).
//
// Sixty-four articles that each answer ONE distinct Medicaid planning question, told
// through a fictional Floridian with a name, a city, assets and a specific problem, in a
// format chosen per piece (timeline, checklist, comparison, worked math, case study,
// myth list, letter, decision tree, Q&A). Same pipeline as the daily article: the
// batch runner (batch.js) feeds each object below to daily-article.js --topic-json.
//
// Every persona is invented. Never a real client's facts.
// Evidence for the cluster: Search Console 9/24/2026, 700 elder/Medicaid queries,
// 3,245 impressions, 0 clicks, positions 30–90 (vault: Medicaid Planning Content Engine).

const SERIES_RULES = `This article is one of a series of about sixty Truestead pieces on Florida Medicaid planning, and each piece answers ONE question. Truestead already publishes a general Medicaid eligibility guide, a five-year-lookback explainer, a "does Medicaid take your house" piece, a nursing-home-cost piece, and a lady bird deed explainer, so do NOT restate the general eligibility rules beyond a sentence or two of orientation. Stay on this article's question. Anchor the whole piece in the fictional example below: introduce the person by first name in the opening, return to them in at least two sections, and resolve what the planning did (or would do) for them in the Truestead Takeaway. Say once, naturally, that the person is a composite and not a client. Follow the stated format. If a current-year dollar figure or divisor cannot be confirmed in the research, describe the rule in words without the number. Write with varied sentence rhythm; never open with "If you're like most Floridians" or "Navigating"; no em-dashes.`;

const SCENES = [
  'an adult daughter and her elderly father reading papers together on a screened Florida lanai at golden hour',
  'a retired couple walking slowly along a quiet Florida beach boardwalk in soft morning light',
  'an elderly woman watering orchids on the porch of a modest Florida bungalow, warm light',
  'a family kitchen table in a Florida home with a folder of documents, coffee cups, and a window of palms',
  'a calm Florida nursing home garden courtyard with benches and a fountain, late afternoon',
  'an older man on a fishing pier at sunrise on the Florida coast, calm water',
  'a tidy Florida ranch house with a flag and citrus tree under a clear sky',
  'grandparents and grandchildren on a Florida dock at dusk, warm and unhurried',
  'a closed manila folder, reading glasses, and keys on a wooden desk with Florida sun through blinds',
  'a quiet assisted-living lobby with sunlight, potted palms, and a woman with a walker',
];

let n = 0;
function t(o) {
  const scene = o.scene || SCENES[n++ % SCENES.length];
  return {
    id: 'medicaid-' + o.id,
    tag: 'Elder Law',
    eyebrow: 'Florida Medicaid Planning',
    category: o.category,
    audience: o.audience || 'Florida families facing long-term care costs and the adult children helping a parent',
    cta: 'consult',
    imageScene: scene,
    description: `${SERIES_RULES}\n\nTHE QUESTION: ${o.q}\nTHE PERSON: ${o.persona}\nFORMAT: ${o.format}\nCOVER: ${o.cover}`,
    searchQueries: o.queries,
  };
}

export const MEDICAID_TOPICS = [

  // ── Gateway and "how it works" ─────────────────────────────────────────────
  t({ id: 'does-medicare-pay-nursing-home', category: 'Does Medicare Pay for Nursing Home Care in Florida?',
    q: 'Does Medicare pay for a nursing home in Florida, and what happens when it stops?',
    persona: 'Frank, 81, Ormond Beach, a retired postal worker who broke his hip, spent four nights in the hospital, and was moved to a skilled nursing facility for rehab. His son Mike assumes Medicare covers the stay.',
    format: 'A day-by-day timeline of the Medicare skilled-nursing benefit (the qualifying hospital stay, the full-coverage days, the copay days, day 101) with what Frank and Mike learn at each step, then the Medicaid pivot.',
    cover: 'Medicare skilled vs custodial care; the three-day inpatient rule and observation status; the copay window; "plateau" and the Jimmo settlement in plain terms; why families are blindsided; what Medicaid long-term care covers instead; when to call an elder law attorney (before day 100, not after).',
    queries: ['Medicare skilled nursing facility coverage 100 days 2026 copay', 'Medicare does not cover custodial long-term care', 'observation status vs inpatient three day rule Medicare SNF', 'Florida Medicaid nursing home coverage after Medicare ends'] }),

  t({ id: 'medicare-vs-medicaid-long-term-care', category: 'Medicare vs Medicaid for Long-Term Care in Florida',
    q: 'What is the difference between Medicare and Medicaid when a Florida parent needs long-term care?',
    persona: 'Denise, 58, Port Orange, comparing the two programs for her mother Ruth, 84, who has early dementia and a paid-off condo in Daytona Beach Shores.',
    format: 'A side-by-side comparison built as a table (who runs it, who qualifies, what it pays for in long-term care, how long, what it costs the family, what it does to the estate), with Denise walking through each row.',
    cover: 'Federal insurance vs needs-based program; dual eligibility and who pays first; what each covers for nursing home, assisted living and home care; why "Mom has Medicare" is not a plan; how Florida Medicaid long-term care is actually reached.',
    queries: ['difference between Medicare and Medicaid long-term care Florida', 'dual eligible Medicare Medicaid Florida nursing home', 'Florida Statewide Medicaid Managed Care Long-Term Care program overview', 'Medicare vs Medicaid assisted living Florida'] }),

  t({ id: 'income-cap-qualified-income-trust', category: 'Florida Medicaid Income Cap and the Qualified Income Trust',
    q: 'My mother\'s income is a little over the Florida Medicaid limit. Is she out of luck?',
    persona: 'Gloria, 79, DeLand, a retired Volusia County schoolteacher whose pension plus Social Security lands a few hundred dollars over the monthly income cap. Her daughter Angela was told at the facility that Gloria "makes too much."',
    format: 'A problem-and-solution walkthrough: the cap, why Florida is an income-cap state, how a Qualified Income Trust (Miller trust) works month to month, what Gloria\'s daughter actually has to do each month, and the mistakes that get applications denied.',
    cover: 'Income cap states; gross vs net income; the QIT mechanics (trust account, monthly deposit, state as remainder beneficiary); patient responsibility after the QIT; what happens if a deposit is missed; that the trust holds income not assets.',
    queries: ['Florida Medicaid income cap 2026 qualified income trust', 'Miller trust Florida how it works monthly deposit', 'Florida Medicaid income limit over the cap denied', 'qualified income trust Florida DCF requirements'] }),

  t({ id: 'lookback-one-family-gifts', category: 'The Five-Year Lookback Through One Family\'s Gifts',
    q: 'Which of the ordinary things Grandma did over the last five years count as Medicaid transfers?',
    persona: 'Evelyn, 86, New Smyrna Beach, who over five years paid a grandson\'s tuition, gave her old car to a granddaughter, tithed generously, helped a son with a down payment, and put a daughter on her checking account.',
    format: 'A case study that walks through each of Evelyn\'s five actions and sorts them: penalized transfer, defensible, or not a transfer at all, with the reasoning for each.',
    cover: 'What the lookback actually looks for; fair market value; gifts vs payments for services; charitable giving; adding a child to an account; documentation that saves a family; the difference between the lookback period and the penalty period.',
    queries: ['Florida Medicaid five year lookback what counts as a transfer', 'Medicaid lookback gifts to grandchildren tuition penalty', 'Medicaid transfer penalty charitable donations Florida', 'adding child to bank account Medicaid lookback'] }),

  t({ id: 'penalty-period-math', category: 'How the Florida Medicaid Penalty Period Is Calculated',
    q: 'Walter gave his son $60,000 two years ago. How long is he ineligible, and when does the clock start?',
    persona: 'Walter, 83, Palm Coast, a widower who gave his son $60,000 toward a business in 2024 and now needs nursing home care.',
    format: 'Worked math, step by step: the transfer amount, the penalty divisor concept, months of ineligibility, and the trap that the penalty does not start until Walter is otherwise eligible and has applied.',
    cover: 'The divisor and where it comes from (do not state a figure unless confirmed by research); partial months; when the penalty clock starts; the "otherwise eligible" requirement; the return-of-gift cure; why a penalty during private pay is the worst outcome.',
    queries: ['Florida Medicaid transfer penalty divisor 2026', 'Medicaid penalty period when does it start otherwise eligible', 'Medicaid gift return cure penalty Florida', 'how to calculate Medicaid penalty period Florida'] }),

  t({ id: 'spend-down-checklist', category: 'Florida Medicaid Spend-Down: What You Are Allowed to Buy',
    q: 'A widow has $180,000 in the bank and a nursing home bill coming. What can she spend it on without a penalty?',
    persona: 'Marjorie, 82, Ormond Beach, a widow with $180,000 in savings, a paid-off home, and a daughter Carol who is afraid every check will be "counted against" her.',
    format: 'A checklist article: allowed spend-down categories with one-line explanations, then the categories that look allowed but are not, with Marjorie\'s own list as the running example.',
    cover: 'Paying legitimate debts; home repairs and accessibility; prepaid funeral; a car; medical equipment; paying for care at fair value; caregiver agreements; what is NOT spend-down (gifts, below-market sales, paying family without a contract); keeping receipts.',
    queries: ['Florida Medicaid spend down allowed purchases', 'Medicaid spend down home repairs prepaid funeral car exempt', 'what can you spend money on before applying for Medicaid Florida', 'Medicaid spend down rules Florida DCF'] }),

  t({ id: 'community-spouse-protections', category: 'Protecting the Spouse at Home in Florida Medicaid Planning',
    q: 'When Bob goes into a nursing home, how much can Carol keep, and how much income can she have?',
    persona: 'Bob and Carol, 78 and 76, Port Orange, married 52 years, with $290,000 in joint savings, a paid-off home, and Bob\'s pension being the larger income.',
    format: 'A two-part explainer: first the resource side (the community spouse resource allowance, what counts, the snapshot date), then the income side (the monthly maintenance needs allowance and how income is shifted to Carol), each illustrated with Bob and Carol\'s numbers described in words.',
    cover: 'The snapshot; the CSRA floor and ceiling concepts; the home, one car, and personal property as exempt; the MMMNA and shifting income; a fair-hearing increase for high shelter costs; why the healthy spouse should never impoverish herself.',
    queries: ['Florida Medicaid community spouse resource allowance 2026', 'minimum monthly maintenance needs allowance Florida 2026', 'Medicaid spousal impoverishment rules Florida snapshot date', 'community spouse income allowance Florida nursing home'] }),

  t({ id: 'intent-to-return-home', category: 'The "Intent to Return Home" Rule in Florida Medicaid',
    q: 'Rosa is in a nursing home and may never go home. Does the house still stay exempt?',
    persona: 'Rosa, 88, Deltona, whose home sits empty while she is in a nursing home. Her son wants to know whether the house must be sold, and whether it matters that her doctor thinks she will not return.',
    format: 'A myth-versus-rule piece: five things families believe about the empty house, each answered with the actual Florida rule and applied to Rosa.',
    cover: 'The homestead exemption while the applicant is alive; the intent-to-return statement and that it is subjective; when a spouse or dependent relative lives there; the home equity limit; renting the house out and income; what changes at death (estate recovery) and why a lady bird deed matters.',
    queries: ['Florida Medicaid intent to return home exempt homestead', 'Medicaid empty house exempt nursing home Florida', 'Florida Medicaid home equity limit 2026', 'renting out home while on Medicaid Florida income'] }),

  t({ id: 'lady-bird-deed-mistakes', category: 'Lady Bird Deed Mistakes That Break a Florida Medicaid Plan',
    q: 'The family used a lady bird deed. Why is the Medicaid application still in trouble?',
    persona: 'Hector, 80, Kissimmee, whose nephew downloaded a lady bird deed form. It named the wrong grantees, was signed with one witness, and was recorded after Hector had already added his daughter as a joint owner.',
    format: 'A failure-mode list: six real ways a lady bird deed goes wrong (bad form, witnesses, wrong grantees, prior joint ownership, title insurance and lender issues, forgetting the contingent beneficiary), each with what it did to Hector and how the fix works.',
    cover: 'What the enhanced life estate deed is supposed to do for Medicaid (no transfer, avoids probate, avoids recovery); execution requirements for a Florida deed; the difference from a regular life estate deed (that one IS a transfer); homestead and spouse joinder; when a trust is the better tool.',
    queries: ['lady bird deed Florida mistakes Medicaid', 'enhanced life estate deed vs life estate deed Medicaid transfer', 'Florida deed execution requirements two witnesses', 'lady bird deed homestead spouse joinder Florida'] }),

  t({ id: 'asset-protection-trust-planning-ahead', category: 'The Florida Medicaid Asset Protection Trust for People Planning Ahead',
    q: 'Diane is 68 and healthy. Is an irrevocable Medicaid trust the right move now?',
    persona: 'Diane, 68, Vero Beach, recently retired, healthy, with a $450,000 home, $300,000 in savings, and a mother who lost everything to nursing home bills.',
    format: 'A decision article: what the trust is, what Diane gives up, what she keeps (income, the right to live in the house, the ability to change beneficiaries in some designs), the five-year timing, and the questions she should answer before signing.',
    cover: 'Irrevocable vs revocable; grantor trust tax treatment and the step-up in basis; the homestead inside the trust; retained income; trustee choice; the lookback clock starting at funding; who this is wrong for.',
    queries: ['Medicaid asset protection trust Florida how it works', 'irrevocable trust five year lookback Florida Medicaid', 'Medicaid trust homestead Florida step up in basis', 'who should not use a Medicaid asset protection trust'] }),

  t({ id: 'crisis-planning-90-day-plan', category: 'Florida Medicaid Crisis Planning: The 90-Day Plan',
    q: 'Dad is already in the nursing home with $300,000. Is it too late to protect anything?',
    persona: 'Raymond, 84, Daytona Beach, admitted last month after a stroke, single, with $300,000 in savings and a home. His daughter Tanya was told by a friend that "it\'s too late for planning."',
    format: 'A 90-day plan in three 30-day blocks: what gets done in the first month (documents, snapshot, exempt purchases), the second (the transfer-and-annuity or gift-and-loan design), the third (the application and QIT if needed), with Raymond\'s outcome.',
    cover: 'Crisis planning exists and works; the difference between preserving half and losing all; the caregiver contract, exempt purchases, Medicaid-compliant annuity, gift-and-annuity ("half a loaf"); the application timing; what "too late" actually means.',
    queries: ['Florida Medicaid crisis planning already in nursing home', 'half a loaf Medicaid planning Florida gift and annuity', 'Medicaid crisis planning strategies single applicant', 'Medicaid compliant annuity Florida crisis'] }),

  t({ id: 'caregiver-agreement', category: 'Paying a Family Caregiver Without a Medicaid Penalty in Florida',
    q: 'Can Dad pay his daughter for the care she already gives him, and will Medicaid count it as a gift?',
    persona: 'Louis, 87, Edgewater, whose daughter Nicole left her job to care for him full time. He wants to pay her $2,500 a month from his savings.',
    format: 'A how-it-works piece built around a sample agreement outline (parties, duties, hours, rate, records) and the three tests DCF applies, with Louis and Nicole\'s arrangement as the example.',
    cover: 'Personal services contracts; fair market rate and written agreement in advance; no payment for past care; logs and 1099 income for the caregiver; lump-sum prepaid contracts and their risks; why "just paying her" without a contract is a penalized transfer.',
    queries: ['personal services contract Medicaid Florida caregiver agreement', 'paying family caregiver Medicaid transfer penalty Florida', 'Medicaid caregiver agreement fair market value documentation', 'lump sum personal care contract Medicaid Florida'] }),

  t({ id: 'medicaid-compliant-annuity', category: 'Medicaid-Compliant Annuities in Florida, Explained',
    q: 'The healthy spouse has a $250,000 IRA. How does a Medicaid-compliant annuity turn it into protected income?',
    persona: 'Helen, 74, Palm Coast, whose husband George is entering memory care. Her $250,000 IRA pushes the couple over the resource allowance.',
    format: 'A mechanism explainer: the problem (excess resources), the move (convert to an irrevocable, non-assignable, actuarially sound annuity naming the state as remainder beneficiary), the result (income to Helen, not a countable asset), and the traps.',
    cover: 'The federal requirements for a Medicaid-compliant annuity; state as remainder beneficiary; term no longer than life expectancy; qualified vs non-qualified funds and taxes; why a regular deferred annuity does not work; the difference between spouse and applicant annuities.',
    queries: ['Medicaid compliant annuity Florida requirements state remainder beneficiary', 'community spouse annuity Medicaid excess resources', 'IRA Medicaid annuity taxes Florida', 'Medicaid annuity actuarially sound life expectancy'] }),

  t({ id: 'iras-401ks-florida-medicaid', category: 'IRAs and 401(k)s in Florida Medicaid Eligibility',
    q: 'Does Florida count a retirement account, and does taking required distributions change that?',
    persona: 'Pete, 70, Clearwater, with a $400,000 401(k) from thirty years at a utility, a modest pension, and a new Parkinson\'s diagnosis.',
    format: 'A Q&A article: eight questions Pete asked in the order he asked them, each answered plainly.',
    cover: 'Florida\'s treatment of retirement accounts in payout status vs not; the difference between applicant and spouse accounts; taxes on liquidation; the annuity route; the disabled-child exception for beneficiaries; why the answer differs by state and why out-of-state articles mislead Floridians.',
    queries: ['Florida Medicaid IRA 401k countable asset payout status', 'Florida Medicaid retirement accounts exempt required minimum distribution', 'spouse IRA Medicaid Florida countable', 'liquidating 401k for Medicaid taxes Florida'] }),

  t({ id: 'joint-accounts-adult-children', category: 'Joint Bank Accounts With Adult Children and Florida Medicaid',
    q: 'Mom added me to her account years ago. Is that money hers, mine, or a gift?',
    persona: 'Susan, 61, Sanford, added to her mother Edna\'s checking and savings "for convenience" in 2019. Edna now needs care and the accounts hold $95,000.',
    format: 'A case study with the three questions DCF asks about a joint account (whose deposits, whose withdrawals, when was the name added), what Susan\'s records showed, and the cleanup.',
    cover: 'Presumption that the applicant owns the whole account; rebutting with contribution records; withdrawals by the child as transfers; convenience vs true joint ownership; the better tools (POA, pay-on-death); fixing it before the application.',
    queries: ['joint bank account Medicaid eligibility adult child Florida', 'Medicaid joint account presumption applicant owns all', 'convenience account vs joint ownership Florida Medicaid', 'child withdrawals from joint account Medicaid transfer'] }),

  t({ id: 'selling-house-before-applying', category: 'Selling the House Before a Florida Medicaid Application',
    q: 'Should the family sell Mom\'s house before applying, and what happens to the money?',
    persona: 'Beverly, 85, South Daytona, whose children want to sell her $320,000 home to "simplify things" before she applies for nursing home Medicaid.',
    format: 'A decision tree: keep the exempt home vs sell; if sold, what the proceeds become; the paths for the proceeds (spend down, annuity, trust, gift with penalty); and the outcome Beverly\'s family chose.',
    cover: 'The home as an exempt asset vs cash as countable; timing a sale relative to the application; capital gains and the primary residence exclusion; estate recovery on the retained home vs nothing to recover if sold and spent; the lady bird deed alternative that keeps the exemption and avoids recovery.',
    queries: ['selling house before Medicaid application Florida proceeds countable', 'Medicaid exempt home vs cash Florida sell or keep', 'Medicaid estate recovery Florida homestead heirs', 'capital gains selling parents home Medicaid'] }),

  t({ id: 'assisted-living-does-medicaid-pay', category: 'Does Florida Medicaid Pay for Assisted Living?',
    q: 'Mom needs assisted living, not a nursing home. Will Florida Medicaid cover it?',
    persona: 'Irene, 83, Ormond Beach, who needs help with medications, meals and bathing but not skilled nursing. Her son Kevin found an ALF at $4,800 a month.',
    format: 'An expectations piece: what the Long-Term Care waiver pays in an ALF (services) vs what it does not (room and board), how the waitlist works, what Irene\'s family actually pays, and the facilities that accept the program.',
    cover: 'SMMC Long-Term Care program; ALF services vs room and board; the Optional State Supplementation concept; waitlist and priority; finding a Medicaid-contracted ALF; private pay bridge planning.',
    queries: ['Florida Medicaid assisted living facility coverage room and board', 'Statewide Medicaid Managed Care Long-Term Care waiver ALF', 'Florida Medicaid ALF waitlist 2026', 'Optional State Supplementation Florida assisted living'] }),

  t({ id: 'home-care-medicaid-waiver', category: 'Staying at Home With Florida Medicaid Long-Term Care',
    q: 'Dad wants to stay in his house. Can Medicaid pay for care at home in Florida?',
    persona: 'Arthur (no relation to the author; call him Art), 89, Holly Hill, a Korean War veteran who refuses to leave the house he built. His daughter needs help four hours a day.',
    format: 'A path article: the screening call, the assessment and priority score, the waitlist, enrollment in a managed care plan, and what services arrive, with Art\'s timeline.',
    cover: 'Home and community-based services under the LTC waiver; the CARES/ADRC screening; priority scoring; what services are covered at home; the participant-directed option; combining with VA benefits; realistic waits.',
    queries: ['Florida Medicaid home care waiver long-term care program eligibility', 'Florida ADRC CARES assessment priority score waitlist', 'Medicaid participant directed option Florida family caregiver paid', 'Florida long-term care Medicaid home and community based services'] }),

  t({ id: 'ltc-waitlist-priority-score', category: 'The Florida Medicaid Long-Term Care Waitlist and Priority Score',
    q: 'Why is there a waitlist for home and assisted-living Medicaid, and how does someone move up?',
    persona: 'Norma, 81, DeBary, screened months ago and still waiting, while her daughter pays a home aide out of pocket.',
    format: 'An explainer of the priority scoring system (what the questions measure, what a high score looks like, when scores are rescreened) and the events that move a person up or bypass the list, told through Norma\'s two screenings.',
    cover: 'Why nursing home Medicaid has no waitlist but the waiver does; the screening and score ranges in words; rescreening after a change; nursing home transition and other bypass paths; what to do while waiting.',
    queries: ['Florida long-term care Medicaid waitlist priority score explained', 'Florida LTC waiver waitlist release 2026', 'how to get off Florida Medicaid waiver waitlist faster', 'Florida nursing home transition Medicaid waiver bypass waitlist'] }),

  t({ id: 'dementia-no-power-of-attorney', category: 'Medicaid Planning When a Parent Has Dementia and No Power of Attorney',
    q: 'Mom can no longer sign anything. How does the family plan for Medicaid now?',
    persona: 'Lorraine, 86, Ocala, with advanced dementia and no durable power of attorney. Her son Greg needs to sell a car, move money, and apply.',
    format: 'A branching article: what can still be done without authority, what requires guardianship, what a guardian can and cannot do for Medicaid planning (and the court approval it takes), and the timeline Greg faced.',
    cover: 'Capacity and why a POA signed now may be void; guardianship basics and cost in plain terms; a guardian\'s limited authority to gift or restructure; court-approved Medicaid planning; why every family should sign the POA before this article applies to them.',
    queries: ['Florida guardianship Medicaid planning court approval gifting', 'parent dementia no power of attorney Medicaid application Florida', 'Florida guardian authority transfer assets Medicaid', 'capacity to sign power of attorney Florida dementia'] }),

  t({ id: 'power-of-attorney-medicaid-powers', category: 'The Power of Attorney a Florida Medicaid Plan Actually Needs',
    q: 'Why did the elder law attorney say Dad\'s power of attorney "isn\'t enough" for Medicaid?',
    persona: 'Vince, 77, Titusville, whose bank-form durable power of attorney names his daughter but says nothing about gifts, trusts, or annuities.',
    format: 'A clause-by-clause piece: the specific powers a Florida POA must expressly grant (gifting beyond limits, creating and funding trusts, changing beneficiaries, dealing with retirement accounts, applying for benefits), why Florida requires them to be spelled out, and what Vince\'s form was missing.',
    cover: 'F.S. Chapter 709 and the "superpowers" that must be separately initialed; agent authority to gift and to create trusts; durable vs springing; banks refusing old forms; updating a POA while capacity exists.',
    queries: ['Florida power of attorney superpowers 709.2202 gifting trust', 'durable power of attorney Medicaid planning powers Florida', 'Florida POA authority to create irrevocable trust', 'why bank refused power of attorney Florida'] }),

  t({ id: 'veterans-aid-attendance-vs-medicaid', category: 'Veterans Aid and Attendance vs Medicaid for a Florida Widow',
    q: 'Is the VA pension enough, or does a veteran\'s widow still need Medicaid planning?',
    persona: 'Dorothy, 90, Ormond Beach, widow of a Vietnam-era veteran, in assisted living at $5,200 a month with $110,000 in savings.',
    format: 'A comparison in three acts: what Aid and Attendance would pay Dorothy and its own three-year lookback, what Medicaid would pay and its five-year lookback, and how the two are sequenced for one person.',
    cover: 'The VA pension with Aid and Attendance; net worth limit and the VA lookback; the medical expense deduction; how VA income interacts with Medicaid income; which comes first; planning that satisfies both.',
    queries: ['VA Aid and Attendance 2026 net worth limit lookback', 'Aid and Attendance vs Medicaid assisted living Florida', 'VA pension counted as income for Medicaid Florida', 'surviving spouse Aid and Attendance eligibility'] }),

  t({ id: 'moving-to-florida-late-in-life', category: 'Moving to Florida Late in Life and Medicaid Planning',
    q: 'A parent moving from New York to Florida: what changes for Medicaid, and what has to be redone?',
    persona: 'Sylvia, 82, moving from Long Island to Palm Coast to live near her son, with a New York trust, New York documents, and a co-op sale closing next month.',
    format: 'A move checklist: residency, documents (POA, healthcare surrogate, trust review), the sale proceeds, out-of-state property, and how Florida rules differ from the state she is leaving, with Sylvia\'s move as the thread.',
    cover: 'Florida residency for Medicaid; why New York documents may not do what Florida needs; Florida homestead advantages; the lookback follows the person across state lines; timing a move relative to an application.',
    queries: ['moving to Florida Medicaid eligibility residency requirement', 'out of state power of attorney valid in Florida', 'Medicaid lookback transfers in another state', 'snowbird Florida Medicaid residency nursing home'] }),

  t({ id: 'married-but-separated', category: 'Married but Separated: How Florida Medicaid Counts a Spouse',
    q: 'They have lived apart for ten years but never divorced. Does the spouse\'s money count?',
    persona: 'Theresa, 71, Deltona, separated from her husband for a decade, with her own savings and his refusal to cooperate with any application.',
    format: 'A rules-then-options piece: how the spousal rules apply to a legally married couple regardless of living arrangements, what information the state wants about the absent spouse, and the three routes (cooperation, spousal refusal, divorce) with pros and cons for Theresa.',
    cover: 'Marriage, not cohabitation, controls; the absent spouse\'s assets; spousal refusal and the state\'s right to pursue support; when divorce is actually recommended; the resource allowance the absent spouse can keep.',
    queries: ['Medicaid married but separated spouse assets counted Florida', 'spousal refusal Florida Medicaid', 'Medicaid divorce Florida nursing home spouse', 'estranged spouse Medicaid application refuses to cooperate'] }),

  t({ id: 'second-marriage-protecting-children', category: 'Second Marriages, Medicaid, and Protecting Each Spouse\'s Children',
    q: 'How does a blended-family couple qualify one spouse for Medicaid without spending the other spouse\'s children\'s inheritance?',
    persona: 'Don and Marlene, 80 and 74, Port Orange, married fifteen years, each with adult children from a first marriage and a prenuptial agreement that Medicaid ignores.',
    format: 'A case study: the prenup problem, the two-estate reality, the tools that respect both families (community spouse allowance, spousal annuity, trusts, beneficiary designations, elective share awareness), and the plan they signed.',
    cover: 'Prenups do not bind Medicaid; the healthy spouse\'s allowance and how it is held; annuity naming children after the state; the elective share and the community spouse\'s will; why each spouse\'s documents must be coordinated.',
    queries: ['second marriage Medicaid planning Florida prenuptial agreement', 'community spouse annuity remainder beneficiary children', 'Florida elective share Medicaid community spouse will', 'blended family Medicaid asset protection Florida'] }),

  t({ id: 'life-insurance-and-funeral-contracts', category: 'Life Insurance, Burial Plans, and Florida Medicaid',
    q: 'Does a life insurance policy count against Medicaid, and what about the prepaid funeral?',
    persona: 'Clarence, 84, Bunnell, with a $25,000 whole life policy, a $5,000 term policy through his old union, and no funeral plan.',
    format: 'A sort-and-fix article: each of Clarence\'s policies sorted by face value and cash value rules, then the exempt funeral tools (irrevocable prepaid contract, burial space items) that turned a countable asset into an exempt one.',
    cover: 'Face value threshold and cash surrender value; term policies; irrevocable funeral trusts and preneed contracts under Florida law; burial spaces; naming the funeral home; what remains to the estate.',
    queries: ['Florida Medicaid life insurance cash value countable face value limit', 'irrevocable prepaid funeral contract Medicaid Florida exempt', 'burial space exemption Medicaid Florida', 'Medicaid life insurance ownership transfer penalty'] }),

  t({ id: 'vehicles-boats-rvs', category: 'Cars, Boats, and RVs in a Florida Medicaid Application',
    q: 'Dad has a truck, a bass boat and a motorhome. What does Florida Medicaid do with them?',
    persona: 'Earl, 79, Astor, a retired lineman with a pickup, a bass boat, a travel trailer, and a classic Mustang under a tarp.',
    format: 'An inventory article: Earl\'s four vehicles run through the exemption rules one by one, then the choices for the rest (sell at fair value and spend down, transfer to a spouse, keep and count).',
    cover: 'One vehicle exempt regardless of value; other vehicles as countable at equity value; boats and RVs; titled to a spouse; selling to a family member at fair value with documentation; the recreational vehicle as a residence question.',
    queries: ['Florida Medicaid one vehicle exemption value', 'Medicaid countable assets boat RV second car Florida', 'selling car to family member fair market value Medicaid', 'Medicaid vehicle exemption spouse Florida'] }),

  t({ id: 'rental-property-medicaid', category: 'Rental Property and Florida Medicaid Eligibility',
    q: 'Mom owns a duplex that pays her $1,600 a month. Is it an asset, income, or both?',
    persona: 'Phyllis, 83, Daytona Beach, who owns the duplex her late husband bought in 1988 and lives on its rent plus Social Security.',
    format: 'A both-sides explainer: the duplex as a countable asset (and the income-producing property exception in words), the rent as income for the cap and patient responsibility, and the four options Phyllis weighed (sell, keep as income-producing, transfer with penalty, trust).',
    cover: 'Income-producing property rules; net rental income; the QIT if rent pushes income over the cap; estate recovery on non-homestead real estate; the lookback on transferring the duplex; capital gains on sale.',
    queries: ['Florida Medicaid rental property countable income producing exemption', 'rental income Medicaid income cap Florida qualified income trust', 'Medicaid estate recovery rental property Florida', 'transfer rental property to children Medicaid penalty'] }),

  t({ id: 'small-business-owner', category: 'Medicaid Planning for a Florida Small Business or Farm Owner',
    q: 'Dad still owns the family business. How does Florida Medicaid treat it when he needs care?',
    persona: 'Manuel, 76, Pierson, who owns a fern nursery with land, equipment, and a son who runs it day to day.',
    format: 'A case study: the business as an asset (valuation, the income-producing property rules, what is exempt as essential to self-support), the succession tools (buy-sell agreement, transfer to the working son and its penalty, sale for fair value), and the route Manuel took.',
    cover: 'Business property essential to self-support; valuing a closely held business; transfers to a child who works the business; agricultural land; the interplay with estate planning and the step-up in basis; timing.',
    queries: ['Medicaid business assets essential to self support exemption Florida', 'transfer family business to child Medicaid lookback', 'Florida farm land Medicaid eligibility', 'valuing small business for Medicaid application'] }),

  t({ id: 'estate-recovery-after-death', category: 'Florida Medicaid Estate Recovery: The Letter the Family Gets',
    q: 'Mom died on Medicaid and a letter arrived from the state. What can it actually take?',
    persona: 'The Ramirez family, Deltona, three siblings who received a recovery notice for their mother Luz\'s 26 months of nursing home Medicaid, with a house in her name and a small bank account.',
    format: 'A letter-in-hand walkthrough: what the notice is, what the probate estate includes, why Florida homestead passing to heirs is generally protected, what is not protected, how the claim is handled in probate, and how the Ramirez family resolved it.',
    cover: 'F.S. 409.9101 in plain terms; recovery limited to the probate estate; the homestead descending to heirs; hardship waivers; the surviving spouse and disabled child exceptions; timing and the creditor period; how a lady bird deed or trust would have changed the outcome.',
    queries: ['Florida Medicaid estate recovery program 409.9101 probate estate', 'Florida Medicaid estate recovery homestead protected heirs', 'Medicaid estate recovery hardship waiver Florida', 'AHCA Medicaid estate recovery notice what to do'] }),

  t({ id: 'denied-excess-assets-appeal', category: 'Denied Florida Medicaid for Excess Assets: The Fair Hearing',
    q: 'The application was denied. What are the options, and how does a fair hearing work?',
    persona: 'The Okafor family, Orlando, whose father Emmanuel was denied because a forgotten $14,000 CD surfaced, and whose 90-day appeal window is running.',
    format: 'A procedure article in order: reading the notice, the deadline, the choice between fixing and reapplying vs appealing, what a fair hearing looks like, evidence that wins, and what happened to Emmanuel.',
    cover: 'Notice of case action; the appeal deadline; hearings before DCF hearing officers; curing excess assets and retroactive eligibility; when to reapply instead; representation at the hearing.',
    queries: ['Florida Medicaid denial appeal fair hearing deadline', 'Medicaid denied excess assets what to do Florida', 'DCF fair hearing Medicaid long-term care Florida', 'retroactive Medicaid eligibility Florida nursing home'] }),

  t({ id: 'access-application-diy', category: 'Applying for Florida Nursing Home Medicaid Yourself Through ACCESS',
    q: 'What does the Florida ACCESS application actually ask, and where do families get tripped up?',
    persona: 'Brenda, 63, Port Orange, applying for her father Charles online at her kitchen table with five years of bank statements in a laundry basket.',
    format: 'A section-by-section guide to the application (identity, income, assets, transfers, insurance, the five-year records), with the six places Brenda got stuck and how each was resolved.',
    cover: 'The ACCESS portal; the level-of-care requirement; the 60-month statements; the questions about transfers and life insurance; the interview; timelines for a decision; when do-it-yourself is reasonable and when it is not.',
    queries: ['Florida ACCESS Medicaid application nursing home documents required', 'Florida Medicaid application five years bank statements', 'DCF Medicaid long-term care application interview timeline', 'level of care determination Florida Medicaid CARES'] }),

  t({ id: 'when-to-start-three-ages', category: 'When to Start Medicaid Planning in Florida: 55, 65, and 75',
    q: 'What can a person still do at 55, at 65, and at 75, and what closes at each age?',
    persona: 'Three people: Janet, 55, Lake Mary, a nurse with aging parents; Ron, 65, Palm Coast, newly retired; and Alice, 75, Ormond Beach, with mild memory changes.',
    format: 'Three parallel profiles, each with "what is open," "what is closing," and "the one thing to do this year," ending with the common thread.',
    cover: 'Long-term care insurance windows; the five-year clock and irrevocable trusts; documents that must be signed while capacity exists; the value of a plan review every few years; why waiting for a diagnosis is the expensive path.',
    queries: ['when to start Medicaid planning Florida age', 'long-term care insurance vs Medicaid planning age 55 65', 'Medicaid planning before diagnosis Florida five year lookback', 'estate plan review elder law Florida'] }),

  t({ id: 'nursing-home-costs-by-region-math', category: 'What a Florida Nursing Home Costs by Region, and How Long $500,000 Lasts',
    q: 'How fast does a nest egg disappear at Florida nursing home prices, region by region?',
    persona: 'The Whitfield siblings, Jacksonville, with a mother in Daytona Beach and $500,000 of her savings, arguing about whether planning is "worth it."',
    format: 'Worked math in words and a simple table: the monthly cost ranges the research supports for several Florida regions, months of coverage for $500,000 at each, and the difference planning made in the Whitfields\' case.',
    cover: 'Cost survey data from the research only; private room vs semi-private; the annual rate of increase; the average length of stay; what "spend down to $2,000" means in months; what proper planning typically preserves.',
    queries: ['Florida nursing home cost per month 2026 by region', 'Genworth cost of care survey Florida 2026 nursing home', 'average nursing home stay length Florida', 'how long do savings last in a nursing home Florida'] }),

  t({ id: 'ltc-insurance-vs-medicaid-planning', category: 'Long-Term Care Insurance vs Medicaid Planning in Florida',
    q: 'Their long-term care premiums doubled. Keep paying, drop it, or plan for Medicaid?',
    persona: 'Herb and Judy, 72 and 70, Ponte Vedra Beach, holding a policy bought in 2004 whose premium just jumped to $9,800 a year.',
    format: 'A three-option analysis (keep, reduce benefits, lapse and plan) with the questions that decide it, then how a policy and a Medicaid plan work together rather than against each other.',
    cover: 'Elimination periods and benefit caps; premium increases and the reduced-benefit option; the Florida Long-Term Care Partnership program and asset disregard; how insurance buys planning time; hybrid life/LTC products.',
    queries: ['long-term care insurance premium increase options reduce benefits', 'Florida Long-Term Care Partnership program asset disregard Medicaid', 'long-term care insurance vs Medicaid planning', 'hybrid life insurance long-term care rider Florida'] }),

  t({ id: 'reverse-mortgage-medicaid', category: 'Reverse Mortgages and Florida Medicaid: The Proceeds Trap',
    q: 'Mom has a reverse mortgage. Does the loan help or hurt a Medicaid application?',
    persona: 'Connie, 84, Holly Hill, with a reverse mortgage line of credit and $60,000 of drawn proceeds sitting in her savings.',
    format: 'A trap-and-fix piece: how the home stays exempt, how drawn proceeds become countable the month after they are received, what happens when Connie moves to a facility (the loan comes due), and the sequence that avoided both problems.',
    cover: 'Reverse mortgage basics; proceeds as income vs asset by month; the residency requirement and the 12-month rule when the borrower leaves; estate recovery and the lender in probate; when to draw and when not to.',
    queries: ['reverse mortgage Medicaid eligibility proceeds countable Florida', 'reverse mortgage due when borrower moves to nursing home', 'HECM proceeds income or asset Medicaid', 'reverse mortgage estate recovery Florida'] }),

  t({ id: 'annual-gift-exclusion-myth', category: 'The $19,000 Gift Myth: Why Annual Exclusion Gifts Still Count for Medicaid',
    q: 'Dad gave each grandchild the annual gift limit every year. Why does Medicaid still penalize it?',
    persona: 'Stan, 82, Winter Park, a retired CPA who gave each of six grandchildren the annual exclusion amount for four years on his accountant\'s advice.',
    format: 'A myth-busting article: the gift tax rule vs the Medicaid transfer rule side by side, the arithmetic of Stan\'s four years of gifts and the penalty they produced, and what could still be done.',
    cover: 'Annual exclusion is a tax concept only; Medicaid penalizes any uncompensated transfer; the total transferred within five years; the return-of-gift cure and partial cures; why CPAs and financial advisors give this advice; the coordination between tax and Medicaid planning.',
    queries: ['annual gift tax exclusion Medicaid lookback penalty myth', 'gifts to grandchildren Medicaid transfer penalty five years', 'gift tax vs Medicaid transfer rules difference', 'return gift cure Medicaid penalty partial'] }),

  t({ id: 'adding-child-to-deed-mistake', category: 'Adding a Child to the Deed: A Florida Medicaid Case Study',
    q: 'The family added a son to Mom\'s deed to "avoid probate." What did that do to her Medicaid plan?',
    persona: 'Margaret, 81, Ormond Beach, who quitclaimed a half interest in her home to her son Paul in 2023 at a title company\'s suggestion.',
    format: 'A before-and-after case study: what the family thought they did, the four problems it created (transfer penalty, loss of full homestead protection, exposure to Paul\'s creditors and divorce, capital gains), and the repair path.',
    cover: 'Half-interest gift as a penalized transfer; homestead and the co-owner\'s creditors; loss of step-up in basis; documentary stamp and title issues; unwinding a deed and whether it cures the penalty; the lady bird deed that should have been used.',
    queries: ['adding child to deed Medicaid transfer penalty Florida', 'quitclaim half interest to child Medicaid lookback', 'child on deed creditors divorce risk Florida homestead', 'undo deed transfer Medicaid penalty cure'] }),

  t({ id: 'revocable-trust-no-protection', category: 'Why a Revocable Living Trust Does Not Protect Assets From Medicaid',
    q: 'They have a living trust. Why doesn\'t it shield anything from nursing home costs?',
    persona: 'Bill and Nancy, 79 and 77, Palm Coast, with a 2015 revocable living trust they believed was "asset protection."',
    format: 'A misunderstanding-corrected piece: what a revocable trust does (probate avoidance, incapacity management), what it does not do (countable assets remain countable), and the two ways Bill and Nancy\'s trust could be adapted.',
    cover: 'Revocable = you still own it for Medicaid; the home inside a revocable trust and the homestead exemption question; converting to an irrevocable structure and the lookback; the trust as the vehicle for a community spouse; keeping the good parts.',
    queries: ['revocable living trust Medicaid countable asset Florida', 'does a living trust protect assets from nursing home', 'revocable trust homestead exemption Medicaid Florida', 'convert revocable trust to irrevocable Medicaid planning'] }),

  t({ id: 'disabled-child-exception', category: 'The Disabled Child Exception in Florida Medicaid Transfers',
    q: 'Can a parent transfer assets to a disabled adult child without a Medicaid penalty?',
    persona: 'Ruth, 80, Sanford, whose son Danny, 52, has been on SSDI since a workplace injury, and who wants her savings to go to him rather than to a nursing home.',
    format: 'A rule-and-design article: the exception itself, the proof of disability the state accepts, why an outright transfer can wreck Danny\'s own benefits, and the special needs trust that solves both problems.',
    cover: 'Exempt transfers to a blind or disabled child; SSA disability determination as proof; supplemental needs trusts (first-party vs third-party); preserving SSI and Medicaid for the child; trustee choice; coordinating with Ruth\'s will.',
    queries: ['Medicaid transfer to disabled child exempt no penalty', 'special needs trust for disabled adult child Medicaid planning parent', 'third party supplemental needs trust Florida', 'transfer assets to disabled child SSI eligibility'] }),

  t({ id: 'pooled-trust-over-65', category: 'Pooled Special Needs Trusts for Florida Medicaid Applicants Over 65',
    q: 'Can an 80-year-old use a pooled trust to become eligible, and does Florida penalize it?',
    persona: 'Leonard, 80, Port Orange, single, with $70,000 over the limit and a nonprofit pooled trust recommended by a facility social worker.',
    format: 'A careful explainer: what a pooled trust is, how it works for someone under 65 vs over 65, Florida\'s treatment of over-65 deposits as transfers (confirm in research; do not assume), what the money can be spent on, and what happens at death.',
    cover: 'Pooled trusts under federal law; the over-65 transfer question in Florida; sole-benefit rules; distributions and in-kind support; payback and the nonprofit retention; comparing to a Medicaid-compliant annuity for Leonard.',
    queries: ['pooled special needs trust over 65 Medicaid transfer penalty Florida', 'pooled trust Florida Medicaid eligibility nursing home', 'first party pooled trust payback Medicaid', 'pooled trust vs Medicaid annuity single applicant'] }),

  t({ id: 'high-value-homestead-equity-cap', category: 'High-Value Florida Homes and the Medicaid Home Equity Limit',
    q: 'Their waterfront home is worth far more than the equity limit. Is Medicaid off the table?',
    persona: 'Gordon and Elaine, 82 and 80, Ponce Inlet, in a paid-off riverfront home worth $1.4 million and with modest savings.',
    format: 'A limit-and-workaround piece: the home equity cap concept, when it does not apply (spouse or dependent living there), the ways to reduce countable equity legitimately, and the plan Gordon and Elaine chose.',
    cover: 'The home equity limit and annual adjustment (state figure only if confirmed); the spouse-at-home exception; reverse mortgage or HELOC to reduce equity and where the cash goes; downsizing; the lady bird deed and estate recovery on a valuable homestead.',
    queries: ['Florida Medicaid home equity limit 2026 exception spouse', 'Medicaid home equity cap reduce equity HELOC', 'high value homestead Medicaid planning Florida', 'Medicaid downsizing home exempt proceeds'] }),

  t({ id: 'patient-responsibility-social-security', category: 'What Happens to the Social Security Check After Florida Medicaid Approval',
    q: 'Once Dad is approved, does he keep his Social Security, or does the nursing home get it?',
    persona: 'Albert, 85, Daytona Beach, approved last month, whose daughter was surprised when the facility asked for his entire Social Security check.',
    format: 'A month-in-the-life article: Albert\'s income, the deductions taken before patient responsibility (personal needs allowance, health insurance premiums, spousal allowance if any), what goes to the facility, and who handles the checks.',
    cover: 'Patient responsibility (share of cost); the personal needs allowance; Medicare and supplemental premiums as deductions; representative payee arrangements; QIT interaction; what happens with a spouse at home.',
    queries: ['Florida Medicaid patient responsibility nursing home income Social Security', 'personal needs allowance Florida Medicaid 2026', 'Medicaid share of cost deductions health insurance premiums', 'representative payee nursing home Medicaid'] }),

  t({ id: 'personal-needs-allowance', category: 'The Personal Needs Allowance: What a Florida Medicaid Resident Keeps',
    q: 'How much money does a nursing home resident on Medicaid actually get to keep each month, and what is it for?',
    persona: 'Mildred, 91, Edgewater, who wants to keep paying for her hair appointments, her church envelope and her granddaughter\'s birthday cards.',
    format: 'A small-numbers article: the allowance concept (state the figure only if confirmed), what it typically covers, the resident trust account at the facility, the asset limit trap when the account grows, and Mildred\'s monthly routine.',
    cover: 'Personal needs allowance; facility resident trust accounts and statements; staying under the asset limit; who can add money; gifts from family and how they are treated; what the facility may and may not charge for.',
    queries: ['personal needs allowance Florida nursing home Medicaid amount', 'nursing home resident trust account Medicaid asset limit', 'what can personal needs allowance be used for', 'family gifts to nursing home resident Medicaid'] }),

  t({ id: 'discharge-planner-72-hours', category: 'The Discharge Planner Said "Apply for Medicaid": The Next 72 Hours',
    q: 'A hospital is discharging Mom to a nursing home and says to apply for Medicaid. What has to happen this week?',
    persona: 'Sharon, 57, DeLand, at her mother Joyce\'s bedside at 4 p.m. on a Friday with a discharge tomorrow and a social worker\'s one-page handout.',
    format: 'An hour-by-hour, then day-by-day action list for the first 72 hours: documents to grab, questions to ask the facility, what not to sign, what not to pay, and who to call, with Sharon\'s weekend as the example.',
    cover: 'Medicare coverage first; the admission agreement and responsible-party clauses; not signing as guarantor; the POA and healthcare surrogate; gathering statements; the snapshot date for a married couple; the first call to an elder law attorney.',
    queries: ['nursing home admission agreement responsible party guarantor Florida', 'hospital discharge to nursing home Medicaid application steps', 'what not to sign nursing home admission Florida', 'Medicaid pending nursing home admission Florida'] }),

  t({ id: 'adult-children-paying-family-loan', category: 'Adult Children Paying for a Parent\'s Care: The Family Loan Trap',
    q: 'The kids have been covering Dad\'s bills. Can they get paid back when he qualifies, and is it a loan or a gift?',
    persona: 'The Nguyen siblings, Orlando, who paid $48,000 of their father Tuan\'s assisted living bills over two years with nothing in writing.',
    format: 'A documentation article: why undocumented family payments are usually treated as gifts to the parent, the promissory note that would have made them loans, whether repayment now is a penalized transfer, and the cleanup the Nguyens did.',
    cover: 'Loans vs gifts in Medicaid; written notes, interest, repayment terms; repaying a legitimate debt as allowed spend-down; when repayment looks like a transfer; keeping a ledger; the caregiver contract alternative.',
    queries: ['family loan to parent Medicaid repayment transfer penalty', 'promissory note Medicaid Florida requirements', 'children paying parents nursing home bills reimbursement Medicaid', 'Medicaid repaying debt to family spend down'] }),

  t({ id: 'single-no-children', category: 'Medicaid Planning for a Single Floridian With No Children',
    q: 'With no spouse and no kids, who is the planning even for, and does it still matter?',
    persona: 'Eleanor, 78, Flagler Beach, never married, no children, a paid-off condo, $240,000 in savings, and a niece she trusts.',
    format: 'A why-and-how piece: the reasons planning still matters (quality of care, control, choice of facility, the niece, charity), the documents Eleanor needs most (POA, surrogate, trust), and the plan that let her keep options open.',
    cover: 'No community spouse protections; choosing an agent and successor; private-pay flexibility as a goal; the irrevocable trust for a chosen beneficiary or charity; the condo and estate recovery; funeral and final-wishes planning.',
    queries: ['Medicaid planning single person no children Florida', 'elder law planning unmarried no heirs power of attorney Florida', 'Medicaid asset protection trust single applicant', 'condo Medicaid exempt Florida single'] }),

  t({ id: 'unmarried-partners', category: 'Unmarried Partners and Florida Medicaid: No Spousal Protections',
    q: 'They have lived together for twenty years but never married. What does that mean when one needs care?',
    persona: 'Carol and Jean, 74 and 71, Gulf Breeze, partners for two decades who own their home as joint tenants and keep separate accounts.',
    format: 'A gap analysis: every spousal protection that does not apply to Carol and Jean (resource allowance, income allowance, exempt transfers between spouses, the home exception), then the substitutes (deed structure, trusts, POA and surrogate naming each other, the marriage question).',
    cover: 'Marriage as the trigger for spousal rules; joint tenancy with right of survivorship and Medicaid; transfers between unmarried partners as penalized; healthcare surrogate and hospital visitation; whether to marry, honestly assessed.',
    queries: ['unmarried couple Medicaid planning Florida no spousal protection', 'domestic partner Medicaid transfer penalty', 'joint tenancy home Medicaid unmarried partner Florida', 'should we marry for Medicaid planning'] }),

  t({ id: 'irrevocable-burial-trust', category: 'The Irrevocable Burial Trust: The Exempt Spend-Down Nobody Uses',
    q: 'What is an irrevocable funeral trust, and why do elder law attorneys recommend it during spend-down?',
    persona: 'Otis, 86, Bunnell, whose daughter needs to reduce $11,000 of excess assets before the application and does not want to "just waste it."',
    format: 'A tool profile: how the irrevocable preneed contract or funeral trust works under Florida law, what can be included, limits and provider choice, how it compares to a life insurance assignment, and Otis\'s arrangement.',
    cover: 'Florida preneed contracts and trusts; irrevocability as the key; goods and services vs cash; changing funeral homes; what happens to any excess at death; the burial space items exemption alongside it.',
    queries: ['irrevocable funeral trust Florida Medicaid spend down', 'preneed funeral contract Florida Medicaid exempt irrevocable', 'Medicaid funeral expense exemption limit Florida', 'life insurance assignment funeral home Medicaid'] }),

  t({ id: 'out-of-state-property', category: 'The Out-of-State Cabin and a Florida Medicaid Application',
    q: 'Mom still owns the lake cabin in Michigan. Does Florida Medicaid count it, and what should be done?',
    persona: 'Marie, 83, Port Orange, a snowbird turned resident who kept the family cabin in northern Michigan that her grandchildren use every summer.',
    format: 'A property decision piece: the cabin as a countable non-homestead asset, the valuation, the options (sell, transfer with penalty, trust, keep and rent), estate recovery and ancillary probate in the other state, and Marie\'s choice.',
    cover: 'Non-homestead real estate anywhere is countable; fair market value evidence; out-of-state transfers and the lookback; ancillary probate and recovery; the family-use trust option; the tax basis question.',
    queries: ['out of state property Medicaid countable asset Florida applicant', 'vacation home Medicaid planning transfer trust', 'ancillary probate Medicaid estate recovery other state', 'family cabin irrevocable trust Medicaid'] }),

  t({ id: 'both-spouses-need-care', category: 'When Both Spouses Need Care: Florida Medicaid Without a Community Spouse',
    q: 'Both parents are declining at the same time. How do the rules work when there is no healthy spouse at home?',
    persona: 'Frank and Rose, 84 and 83, Ormond Beach, both needing assisted living within the same year, with $210,000 and a home.',
    format: 'A two-applicant walkthrough: the couple\'s combined asset limit when both apply, the home when neither lives there, the sequencing (one first, then the other), and the plan that kept them together in the same facility.',
    cover: 'Couple asset limit when both institutionalized; the home losing its exemption if no one intends to return; income for each; keeping spouses in one facility; the trust or annuity design for two; documents for each spouse.',
    queries: ['both spouses nursing home Medicaid asset limit couple Florida', 'Medicaid both spouses institutionalized home exempt', 'married couple both need assisted living Medicaid planning', 'Medicaid planning two applicants same household'] }),

  t({ id: 'medicaid-divorce', category: '"Medicaid Divorce" in Florida: Why Families Ask and Why It Is Rarely the Answer',
    q: 'Would divorcing protect the healthy spouse\'s savings, and what does it cost the family?',
    persona: 'Linda, 72, Winter Springs, whose husband Ken has early-onset Alzheimer\'s and whose financial advisor suggested divorce "to protect the accounts."',
    format: 'An honest assessment: what a divorce would and would not do for Linda, the emotional and legal costs, the equitable-distribution reality, the alternatives that achieve most of the goal (spousal allowances, annuities, spousal refusal), and when divorce is genuinely considered.',
    cover: 'Equitable distribution and support obligations; a guardian ad litem for an incapacitated spouse; the healthy spouse\'s inheritance rights lost; alternatives that preserve the marriage; ethics and candor.',
    queries: ['Medicaid divorce Florida protect assets spouse Alzheimer', 'divorce incapacitated spouse Florida guardian', 'alternatives to Medicaid divorce spousal refusal annuity', 'Medicaid planning married couple keep assets without divorce'] }),

  t({ id: 'spousal-refusal-florida', category: 'Spousal Refusal in Florida Medicaid: What It Is and What It Is Not',
    q: 'Can the spouse at home simply refuse to contribute, and what does the state do about it?',
    persona: 'Barbara, 76, Naples, with $600,000 in her own name and a husband Jerry entering a nursing home.',
    format: 'A rules-and-consequences piece: how spousal refusal works under federal law and Florida practice (confirm current Florida treatment in research), the assignment of support rights, the state\'s option to pursue Barbara, the practical risk, and how it compares to an annuity for her situation.',
    cover: 'Refusal to make resources available; assignment of support rights to the state; the state\'s recovery actions in practice; eligibility of the institutionalized spouse; documentation; when an annuity is safer.',
    queries: ['spousal refusal Florida Medicaid allowed', 'Medicaid spousal refusal state pursue support recovery', 'spousal refusal vs Medicaid compliant annuity', 'Florida DCF spousal refusal policy long-term care'] }),

  t({ id: 'half-a-loaf-strategy', category: 'The Half-a-Loaf Medicaid Strategy in Florida, Worked Out',
    q: 'How does gifting half and using the other half to cover the penalty actually preserve money?',
    persona: 'Walter\'s neighbor Hazel, 85, Palm Coast, single, in a nursing home with $200,000 and no planning done.',
    format: 'A worked example in words: the gift, the penalty it creates, the Medicaid-compliant annuity or promissory note that pays the facility through the penalty, the amount preserved, and the sequence of filings.',
    cover: 'Gift-and-annuity and gift-and-note designs; timing the application to start the penalty; the annuity paying private rates during the penalty; the arithmetic in narrative; risks (death during penalty, rule changes, facility cooperation).',
    queries: ['half a loaf Medicaid strategy gift and annuity explained', 'gift and promissory note Medicaid planning Florida', 'Medicaid crisis planning single applicant preserve half', 'Medicaid annuity during penalty period private pay'] }),

  t({ id: 'what-medicaid-planning-costs', category: 'What Medicaid Planning Costs in Florida and What a Flat Fee Buys',
    q: 'What does hiring an elder law attorney for Medicaid planning cost, and what is included?',
    persona: 'Dennis, 60, Port Orange, comparing a facility\'s "free Medicaid help," a non-lawyer Medicaid planner, and two elder law firms for his mother\'s case.',
    format: 'A buyer\'s guide: the three kinds of help and what each can legally do, what a flat-fee engagement typically includes and excludes, questions to ask, and the red flags Dennis learned to spot. Do not state Truestead\'s own fee; say Truestead quotes a flat fee on the free call.',
    cover: 'Attorneys vs non-attorney Medicaid planners and the unauthorized practice issue; facility-referred help and conflicts; flat fee vs hourly; what a typical engagement covers (analysis, documents, application, hearing); value relative to one month of care.',
    queries: ['how much does a Medicaid planning attorney cost Florida flat fee', 'non-attorney Medicaid planner Florida unauthorized practice', 'what does elder law attorney Medicaid planning include', 'questions to ask Medicaid planning attorney'] }),

  t({ id: 'diy-application-cost-the-house', category: 'The Do-It-Yourself Medicaid Application That Cost a Family the House',
    q: 'What went wrong when a family applied on their own, and what would have changed it?',
    persona: 'The Baxter family, Deltona, whose sister Pam handled their mother\'s application herself, answered a transfer question wrong, missed the intent-to-return statement, and later faced estate recovery on the home.',
    format: 'A narrative case study in four scenes (the application, the denial and reapplication, the approval with a penalty, the letter after death), each with the specific error and the fix that was available.',
    cover: 'Common self-application errors; the transfer question; the homestead intent statement; missed exempt purchases; estate recovery exposure that a lady bird deed would have avoided; when DIY is fine and when it is not.',
    queries: ['Medicaid application mistakes families make Florida', 'Medicaid intent to return home statement missed homestead', 'Medicaid estate recovery house could have been avoided', 'DIY Medicaid application denied Florida'] }),

  t({ id: 'document-checklist-adult-children', category: 'The Medicaid Planning Document Checklist for Florida Adult Children',
    q: 'Before the first call with an elder law attorney, what should the family gather?',
    persona: 'Karen, 55, New Smyrna Beach, the organized daughter who wants to walk into the consultation ready.',
    format: 'A gather-it checklist grouped by category (identity and status, income, assets, real estate, insurance, transfers, existing documents, care and medical), each with why the attorney needs it, plus the three things Karen almost forgot.',
    cover: 'Five years of statements; deeds and mortgage statements; policies; retirement statements; the existing will, trust, POA and surrogate; the level-of-care records; a list of gifts and sales; VA and pension letters.',
    queries: ['documents needed Medicaid planning consultation Florida', 'Medicaid application document checklist five years statements', 'what to bring to elder law attorney meeting', 'Florida Medicaid long-term care required documents list'] }),

  t({ id: 'memory-care-and-medicaid', category: 'Memory Care and Florida Medicaid: When the ALF Does Not Take It',
    q: 'Dad is in a memory care unit that does not accept Medicaid. What happens when the money runs out?',
    persona: 'Sam, 79, Daytona Beach Shores, in a private-pay memory care unit at $7,200 a month with about a year of savings left.',
    format: 'A runway article: calculating the remaining private-pay months, the conversation to have with the facility now, the Medicaid-accepting options (waiver ALFs, nursing home memory units), planning that extends the runway, and the transition Sam\'s family arranged.',
    cover: 'Memory care as ALF or SNF; Medicaid acceptance by facility; the waiver and the waitlist; using the runway for planning (spend-down, caregiver contract, trust for a spouse); avoiding a forced move at the worst time.',
    queries: ['memory care Medicaid Florida assisted living accepts Medicaid', 'Florida memory care cost 2026 private pay Medicaid transition', 'nursing home dementia unit Medicaid Florida', 'planning before money runs out memory care'] }),

  t({ id: 'inheritance-while-on-medicaid', category: 'Inheriting Money While on Florida Medicaid: The 10-Day Rule',
    q: 'Mom is on Medicaid and her brother just left her $40,000. Does she lose coverage?',
    persona: 'Agnes, 88, Ocala, on nursing home Medicaid for two years, whose late brother named her in his will.',
    format: 'A timeline article: the day the inheritance is known, the reporting deadline, the month the money is counted, the options (spend down on exempt items, a pooled trust, disclaimers and why they usually do not work for Medicaid), and Agnes\'s outcome.',
    cover: 'Change reporting within 10 days; lump sum as income in the month received, asset after; ineligibility months; spend-down on exempt items; disclaimers treated as transfers; the beneficiary\'s family planning ahead (a supplemental needs trust in the brother\'s will).',
    queries: ['inheritance while on Medicaid Florida report 10 days', 'Medicaid recipient receives inheritance lose eligibility spend down', 'disclaimer inheritance Medicaid transfer penalty', 'supplemental needs trust in will for beneficiary on Medicaid'] }),

  t({ id: 'pi-settlement-on-medicaid', category: 'A Personal Injury Settlement While on Medicaid: The Special Needs Trust Route',
    q: 'Grandpa was injured in a crash and there is a settlement coming. Does he lose his Medicaid?',
    persona: 'Roland, 74, Port Orange, on the Medicaid long-term care program at home, with a $150,000 settlement from a rear-end collision.',
    format: 'A settlement-to-trust walkthrough: the Medicaid lien on the settlement, the reporting duty, the first-party special needs trust and the pooled trust alternative (and the over-65 question in Florida), what the trust can pay for, payback at death, and Roland\'s result.',
    cover: 'Medicaid third-party liability and lien; timing and reporting; the (d)(4)(A) trust under 65 vs pooled trust; sole benefit and payback; how the trust preserves benefits; coordination between the PI lawyer and the elder law lawyer.',
    queries: ['personal injury settlement Medicaid eligibility special needs trust over 65', 'Florida Medicaid lien personal injury settlement', 'pooled trust personal injury settlement Medicaid Florida', 'reporting settlement to Medicaid Florida'] }),

  t({ id: 'selling-house-after-medicaid-approval', category: 'Selling Mom\'s House After She Is on Medicaid',
    q: 'Now that she is approved and will not return home, can the family sell the house, and what happens to the money?',
    persona: 'Ruby, 87, Deltona, on nursing home Medicaid for a year, with a home her children want to sell rather than maintain.',
    format: 'A sequence article: notifying the state, the proceeds converting from exempt home to countable cash, the month it is counted, the options (spend down, annuity, lady bird deed before sale to a buyer, keeping it rented), and Ruby\'s family\'s choice.',
    cover: 'Loss of exemption on sale; ineligibility and reapplication; exempt spend-down of proceeds; a deed strategy before any sale; the home as rental with income to the QIT; capital gains and the residence exclusion.',
    queries: ['selling house while on Medicaid nursing home Florida proceeds', 'Medicaid recipient sells home lose eligibility spend down proceeds', 'rent out home while on Medicaid Florida', 'lady bird deed before selling home Medicaid'] }),

  t({ id: 'annual-redetermination', category: 'Florida Medicaid Redetermination: Staying Eligible Year After Year',
    q: 'Approval is not forever. What does the yearly review ask, and how do families lose coverage by accident?',
    persona: 'Lucille, 90, Palm Coast, whose son missed a renewal packet in the mail and got a termination notice.',
    format: 'An annual-cycle article: when the review comes, what it asks, the asset creep that causes terminations (resident trust accounts, refunds, small inheritances), the QIT and caregiver-contract upkeep, and how Lucille\'s coverage was restored.',
    cover: 'Renewal timing and notices; reporting changes in between; the $2,000 line and resident accounts; keeping the QIT funded every month; the 90-day reconsideration window after termination; keeping the mailing address current.',
    queries: ['Florida Medicaid redetermination long-term care annual review', 'Medicaid terminated missed renewal reinstate Florida 90 days', 'nursing home Medicaid asset limit exceeded lose eligibility', 'qualified income trust ongoing compliance Medicaid Florida'] }),

  t({ id: 'rehab-ending-30-day-notice', category: 'Rehab Is Ending: The Florida Nursing Home Discharge Notice and the Medicaid Transition',
    q: 'The facility says Medicare rehab days are over and Dad must leave or pay. What are the rights and the plan?',
    persona: 'Ernest, 83, Daytona Beach, told on a Tuesday that his covered days end Friday, with a daughter who lives three hours away.',
    format: 'A rights-and-steps article: the notice the facility must give, the expedited appeal of a Medicare cut-off, the choice between private pay and Medicaid pending, the discharge protections, and Ernest\'s week.',
    cover: 'Notice of Medicare non-coverage and the fast appeal; involuntary discharge rules and required notice; "Medicaid pending" and facility acceptance; converting to long-term care status; the family\'s leverage.',
    queries: ['notice of Medicare non-coverage skilled nursing appeal expedited', 'nursing home involuntary discharge rules Florida 30 day notice', 'Medicaid pending nursing home Florida accept', 'transition from Medicare rehab to long-term care Medicaid'] }),

  t({ id: 'middle-class-gap', category: '"My Parent Has Too Much for Medicaid": The Florida Middle-Class Gap',
    q: 'Not rich, not poor, and a nursing home costs more than the income. Where does planning fit for a middle-class family?',
    persona: 'The Coopers, Port Orange: mother Doris, 82, with $350,000 saved, a paid-off house, and a monthly income that covers about half of a nursing home bill.',
    format: 'A gap analysis: the math of income vs cost in words, why "too much for Medicaid" is a temporary condition, the sequence that converts the gap into a plan (exempt purchases, caregiver contract, annuity or trust, application timing), and where Doris ended up.',
    cover: 'The middle-class squeeze; spend-down to $2,000 as the default outcome; planning as choosing what the money does before it goes; the mix of tools by timeline; the honest tradeoffs.',
    queries: ['middle class family nursing home costs Medicaid planning Florida', 'too much money for Medicaid nursing home what to do', 'Medicaid planning $300,000 savings nursing home', 'spend down vs asset protection nursing home Florida'] }),

  t({ id: 'guardianship-vs-poa-for-medicaid', category: 'Guardianship vs Power of Attorney for Florida Medicaid Planning',
    q: 'Which authority does the family actually need to plan and apply, and what does each allow?',
    persona: 'Two siblings, Orlando: Mark holds their mother Ann\'s durable POA; his sister Julie thinks they need guardianship to "do it properly."',
    format: 'A side-by-side comparison (cost, time, court involvement, authority to plan, authority to gift or fund a trust, ongoing reporting), applied to what Mark and Julie need to do for Ann.',
    cover: 'When a valid POA is enough; when guardianship is required (no POA, capacity gone, family conflict); the court\'s role in approving planning by a guardian; less restrictive alternatives; costs in words.',
    queries: ['guardianship vs power of attorney Medicaid planning Florida', 'Florida guardianship court approval Medicaid planning transfers', 'less restrictive alternative to guardianship Florida', 'durable power of attorney enough for Medicaid application'] }),

  t({ id: 'timeline-from-first-call-to-approval', category: 'From First Call to Approval: A Florida Medicaid Planning Timeline',
    q: 'What does the whole process look like, week by week, from the first phone call to an approval letter?',
    persona: 'The Alvarez family, Sanford, planning for their father Ramón, 81, who has just moved into a nursing home.',
    format: 'A week-by-week timeline (consultation, records, design, documents signed, transfers and purchases, application filed, DCF requests, interview, decision), with what the Alvarez family did each week and the realistic total.',
    cover: 'How long each stage takes; what DCF asks for after filing; the 45-day processing standard and reality; retroactive coverage; where families lose weeks.',
    queries: ['how long does Florida Medicaid application take nursing home', 'Medicaid long-term care approval timeline Florida DCF', 'retroactive Medicaid three months Florida nursing home', 'Medicaid planning process steps elder law'] }),

  t({ id: 'medicaid-and-the-surviving-spouse', category: 'When the Medicaid Spouse Dies First: What the Florida Surviving Spouse Keeps',
    q: 'Bob was on Medicaid and passed away. Does the state come after Carol now?',
    persona: 'Carol, 77, Port Orange, widow of Bob (from the community-spouse article), with the protected savings and the house in her name.',
    format: 'An after-death piece: no recovery while a spouse survives, what happens to the QIT balance, the annuity remainder, the house, and what Carol should do now to protect her own future care.',
    cover: 'Estate recovery deferred while a surviving spouse lives; QIT remainder to the state; annuity remainder order; the survivor\'s own planning window; updating documents; the survivor\'s inheritance rights and Medicaid.',
    queries: ['Medicaid estate recovery surviving spouse Florida deferred', 'qualified income trust remainder state death Florida', 'community spouse after institutionalized spouse dies planning', 'surviving spouse Medicaid planning own care'] }),

  t({ id: 'condo-and-hoa-medicaid', category: 'Condos, HOA Fees, and Florida Medicaid',
    q: 'Mom\'s condo has big assessments coming. Is the condo exempt, and who pays the fees while she is in care?',
    persona: 'Vera, 85, Daytona Beach Shores, in an oceanfront condo facing a milestone-inspection special assessment.',
    format: 'A property-with-obligations article: the condo as homestead, the assessments and fees as allowed expenses during spend-down, what happens when Vera is in a facility, renting the unit, and the estate recovery question for a condo.',
    cover: 'Condo as exempt homestead; special assessments paid from the applicant\'s funds as spend-down; association rules on rentals; keeping the unit vs selling; the lady bird deed for a condo; post-Surfside assessment realities.',
    queries: ['condo exempt homestead Medicaid Florida', 'special assessment paid before Medicaid spend down', 'renting condo while on Medicaid Florida income', 'Florida condo milestone inspection assessment elderly owner'] }),

  t({ id: 'snowbird-two-homes', category: 'Two Homes, One Medicaid Application: Florida Snowbirds and Residency',
    q: 'With a house up north and a condo in Florida, which state, and what happens to the other home?',
    persona: 'Ed and Ginny, 80 and 78, Ormond Beach half the year and Ohio the other half, when Ed needs a nursing home.',
    format: 'A choose-and-consolidate article: deciding the state of residence, why two homes cannot both be exempt, what to do with the second home, the timeline to establish Florida residency, and Ed and Ginny\'s plan.',
    cover: 'State of application and residency; one exempt home; the second home as countable; selling vs transferring vs trust; coordinating documents across two states; Florida\'s advantages.',
    queries: ['snowbird two homes Medicaid which state apply', 'second home countable asset Medicaid Florida', 'establish Florida residency for Medicaid nursing home', 'Medicaid planning two states property'] }),

  t({ id: 'medicaid-for-younger-disabled-adult', category: 'Florida Medicaid Long-Term Care for a Younger Adult With a Disability',
    q: 'A 48-year-old with MS needs long-term care. Do the same Medicaid rules apply as for an 85-year-old?',
    persona: 'Tom, 48, Sanford, with progressive multiple sclerosis, a working wife, two teenagers, and a mortgage.',
    format: 'A same-and-different article: the rules that apply identically (asset limit, lookback, spousal protections), the ones that differ (age-related program paths, SSDI and Medicare waiting period, the disabled-adult trust options under 65), and Tom\'s plan.',
    cover: 'Long-term care Medicaid under 65; SSDI and the Medicare waiting period; first-party special needs trust under 65; the working spouse\'s income and assets; the home with minor children; ABLE accounts briefly.',
    queries: ['Medicaid long-term care under 65 disability Florida', 'special needs trust under 65 self settled Florida', 'spouse works Medicaid long-term care eligibility income', 'SSDI Medicare waiting period Medicaid Florida'] }),

  t({ id: 'medicaid-and-the-family-meeting', category: 'The Family Meeting Before Medicaid Planning: What to Decide Together',
    q: 'Four siblings, one parent, and a plan that moves money. How does a family decide without a fight?',
    persona: 'The Peterson siblings, Orlando and Daytona Beach, deciding who holds the POA, who is paid as caregiver, and what "fair" means for their mother Eileen, 84.',
    format: 'An agenda article: the decisions to make (agent, caregiver, the house, gifts vs trust, who pays what), the questions that cause conflict, the documents that settle them, and how the Petersons ran the meeting.',
    cover: 'Choosing one agent and a successor; caregiver contracts and sibling resentment; equalizing through the estate plan rather than through Medicaid transfers; transparency and accounting; the attorney\'s role as neutral.',
    queries: ['family meeting elder care planning siblings decisions', 'choosing power of attorney among siblings Florida', 'caregiver sibling paid resentment agreement', 'elder law attorney family conflict Medicaid planning'] }),

  t({ id: 'medicaid-planning-and-taxes', category: 'Taxes in Florida Medicaid Planning: Basis, Gifts, and Trusts',
    q: 'What tax mistakes do families make while protecting assets for Medicaid?',
    persona: 'Roger, 79, Windermere, whose son proposed gifting appreciated stock and the house to the kids "to get it out of Dad\'s name."',
    format: 'A tax-lens article: the step-up in basis lost on lifetime gifts, the gift tax return most families never owe, capital gains on the home and the residence exclusion, grantor trust treatment for a Medicaid trust, and the plan that protected Roger\'s assets without the tax hit.',
    cover: 'Carryover vs stepped-up basis; annual exclusion and lifetime exemption reporting; the 121 exclusion on a home; intentionally defective grantor trust concepts in plain terms; Florida has no state income or estate tax; coordination with the CPA.',
    queries: ['Medicaid planning step up in basis gift house to children', 'Medicaid asset protection trust grantor trust taxes', 'gift tax return Medicaid planning gifts children', 'capital gains selling parents home Medicaid trust'] }),
];

export default MEDICAID_TOPICS;
